version: '3.7'

services:
  frontier:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontier
    volumes:
      - ./src:/var/www/html:cached
    ports:
      - "8000:8000"